# Generated by Django 5.0.4 on 2024-05-04 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlawyer', '0023_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlawyer.client'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlawyer.client'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlawyer.lawyer'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlawyer.client'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlawyer.client'),
        ),
    ]
